name: database_adapter_elasticsearch
version: 0.2.2
description:
  Adapter between 'package:database' and Elasticsearch, a full-featured text search engine based on
  Apache Lucene.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  built_value: ^8.0.0
  collection: ^1.14.0
  database:
    git:
      url: https://github.com/Jack-Beattie/database.git
      path: database/
  meta: ^1.1.0
  universal_io: ^2.0.0-nullsafety.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0
